language: java
branches:
  only:
  - master
jobs:
  include:
  - stage: site
    name: "Build guide"
    jdk: oraclejdk8
    script: mvn clean package
deploy:
  condition: env(GITHUB_TOKEN) IS present
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  repo: vietj/advanced-vertx-guide
  target-branch: gh-pages
  local-dir: ./target/docs/advanced-vertx-guide/
  on:
    branch: master
